### ISSUE TITLE
Security issue in project dependencies

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-js#66]
**Describe the bug**
`npm` is warning up about a vulnerability

**Environment information:**

- OS: Linux ciaamq 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux
```.json
{ 'hardware-wallet-js': '1.0.0',
  npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.1',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }
```

**Steps to Reproduce**
Just run `npm audit`

**Actual behavior**
```.bash
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ secure-random@1.1.1
added 1 package from 1 contributor and audited 8230 packages in 5.896s
found 351 vulnerabilities (1 low, 350 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ eslint@5.14.1
added 15 packages from 9 contributors, removed 18 packages and updated 31 packages in 38.668s
fixed 350 of 351 vulnerabilities in 8230 scanned packages
  1 vulnerability required manual review and could not be updated
```

**Expected behavior**
No warnings reported about vulnerability

**Comment by stdevIvr** [comment]
That issue is a bit complicated, because the warnings that `npm audit` is giving to you, are about the dependencies of `your dependencies`, so the way to really fix them, is to take the vulnerable repo, make a fork, update the dependencies and then create a PR, for `EVERY VULNERABILITY`. The other way is to run `npm audit fix` but it might be a bad choice because the "fixed" version that it brings, can have important changes like turn to `deprecated` an important function for the project, etc etc...

**Comment by stdevIvr** [comment]
https://www.voitanos.io/blog/don-t-be-alarmed-by-vulnerabilities-after-running-npm-install

**Comment by olemis** [comment]
this is a wontfix
